version: '1'
services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sistema_control_votantes
      POSTGRES_USER: computos
      POSTGRES_PASSWORD: v0t4nt3s
    volumes:
      #- /Users/marceloambrosio/Documents/DockerVolumes/control_votantes:/var/lib/postgresql/data
      - D:\Users\marce\Documents\DockerVolumes\control_votantes:/var/lib/postgresql/data

volumes:
  postgres_data: