# Generated by Django 4.2.3 on 2023-08-02 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('control', '0003_alter_circuito_seccion_alter_escuela_circuito_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BocaDeUrna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('circuito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.circuito')),
            ],
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('apellido', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_partido', models.IntegerField()),
                ('nombre', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DetalleBocaDeUrna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.CharField(choices=[('16-21', '16 a 21 años'), ('22-30', '22 a 30 años'), ('30-40', '30 a 40 años'), ('50-65', '50 a 65 años'), ('65+', '65 o más años')], max_length=6)),
                ('boca_de_urna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bocadeurna.bocadeurna')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bocadeurna.candidato')),
            ],
        ),
        migrations.AddField(
            model_name='candidato',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bocadeurna.cargo'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='circuito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.circuito'),
        ),
    ]
