# Generated by Django 4.2.3 on 2023-08-30 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BocaDeUrna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DetalleBocaDeUrna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.CharField(choices=[('16-21', '16 a 21 años'), ('22-30', '22 a 30 años'), ('30-40', '30 a 40 años'), ('50-65', '50 a 65 años'), ('65+', '65 o más años')], max_length=6)),
                ('boca_de_urna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bocadeurna.bocadeurna')),
            ],
        ),
    ]
