# Generated by Django 4.2.3 on 2023-09-12 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_remove_tipoeleccion_cargo_cargo_orden_cargo'),
        ('computo', '0002_candidato_partido_candidatoeleccion_candidato_and_more'),
        ('bocadeurna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bocadeurna',
            name='eleccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='control.eleccion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallebocadeurna',
            name='candidato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='computo.candidatoeleccion'),
            preserve_default=False,
        ),
    ]
