# Generated by Django 4.2.3 on 2023-08-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocadeurna', '0002_candidato_partido_alter_candidato_apellido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partido',
            name='num_partido',
        ),
        migrations.AddField(
            model_name='partido',
            name='lista',
            field=models.CharField(default=2),
            preserve_default=False,
        ),
    ]
