# Generated by Django 4.2.3 on 2023-08-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocadeurna', '0003_remove_partido_num_partido_partido_lista'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
