# Generated by Django 4.2.3 on 2023-08-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocadeurna', '0004_partido_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partido',
            name='color',
        ),
        migrations.AddField(
            model_name='candidato',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
