# Generated by Django 4.2.3 on 2023-07-13 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_circuito', models.IntegerField()),
                ('localidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('circuito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='control.circuito')),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('num_mesa', models.IntegerField(primary_key=True, serialize=False)),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='control.escuela')),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_seccion', models.IntegerField()),
                ('departamento', models.CharField()),
            ],
        ),
        migrations.AddField(
            model_name='circuito',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='control.seccion'),
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num_orden', models.IntegerField()),
                ('dni', models.IntegerField()),
                ('apellido', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('clase', models.IntegerField()),
                ('domicilio', models.CharField(max_length=100)),
                ('voto', models.BooleanField(default=False)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='control.mesa')),
            ],
            options={
                'unique_together': {('dni', 'apellido', 'nombre', 'num_orden')},
            },
        ),
    ]
