# Generated by Django 4.2.3 on 2023-07-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='voto',
            field=models.BooleanField(default=False),
        ),
    ]
