# Generated by Django 4.2.3 on 2023-09-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoeleccion',
            name='cargo',
        ),
        migrations.AddField(
            model_name='cargo',
            name='orden_cargo',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
