# Generated by Django 4.2.3 on 2023-07-18 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_alter_persona_mesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuito',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.seccion'),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='circuito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.circuito'),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='escuela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.escuela'),
        ),
    ]
