# Generated by Django 4.2.3 on 2023-09-05 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
                ('apellido', models.CharField()),
                ('color', models.CharField(default='#000000', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='CandidatoEleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Computo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lista', models.CharField()),
                ('nombre', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='DetalleComputo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_voto', models.PositiveIntegerField(blank=True, null=True)),
                ('candidato_eleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computo.candidatoeleccion')),
                ('computo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computo.computo')),
            ],
        ),
    ]
